# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. Matías Alvarado
email: matias@cs.cinvestav.mx
description: 
  Investigador CINVESTAV 3C

  Miembro de la Academia Mexicana de Ciencias

  Miembro Fundador de la Academia Mexicana de Computación AMEXCOMP
biography:
  Professor Matías Alvarado Mentado has a Bachelor degree in
  mathematics from the Universidad Nacional Autónoma de México
  (UNAM). Then, he studied in Universidad Politécnica de Catalunya
  where he obtained a PhD in Artifitial Inteligence. Upon completition
  of his studies he worked for various academic institutions including 
  CINVESTAV and Mexican Petroleum Institute. 

  He is currently working on strategic reasoning in sport, board games 
  and cancer metastasis vs immune system; Ising model for algorithms 
  and simulation for cancer metastasis and the game of Go; Nash 
  equilibrium for strategies choice in baseball, American football 
  and soccer; and	Emotional response regulation.

languages: ['es']
#description1: 
#  Miembro Fundador de la Academia Mexicana de Computación AMEXCOMP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  MatiasAlvaradoM
twitter_username: josematiasal
port: 4000
# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
